# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created: Mon Nov 11 18:53:09 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 547)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 10, 491, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ChatLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.ChatLayout.setContentsMargins(0, 0, 0, 0)
        self.ChatLayout.setObjectName("ChatLayout")
        self.txt_messages = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.txt_messages.setReadOnly(True)
        self.txt_messages.setObjectName("txt_messages")
        self.ChatLayout.addWidget(self.txt_messages)
        self.Messagebar = QtGui.QHBoxLayout()
        self.Messagebar.setObjectName("Messagebar")
        self.txt_message = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.txt_message.setReadOnly(True)
        self.txt_message.setObjectName("txt_message")
        self.Messagebar.addWidget(self.txt_message)
        self.bt_send = QtGui.QPushButton(self.verticalLayoutWidget)
        self.bt_send.setEnabled(False)
        self.bt_send.setObjectName("bt_send")
        self.Messagebar.addWidget(self.bt_send)
        self.ChatLayout.addLayout(self.Messagebar)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 181, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.RoomLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.RoomLayout.setContentsMargins(0, 0, 0, 0)
        self.RoomLayout.setObjectName("RoomLayout")
        self.cmb_userlists = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cmb_userlists.setEnabled(False)
        self.cmb_userlists.setObjectName("cmb_userlists")
        self.RoomLayout.addWidget(self.cmb_userlists)
        self.lst_users = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.lst_users.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lst_users.setObjectName("lst_users")
        self.RoomLayout.addWidget(self.lst_users)
        self.bt_switch = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_switch.setEnabled(False)
        self.bt_switch.setObjectName("bt_switch")
        self.RoomLayout.addWidget(self.bt_switch)
        self.bt_logout = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_logout.setEnabled(False)
        self.bt_logout.setObjectName("bt_logout")
        self.RoomLayout.addWidget(self.bt_logout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bt_ipban = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_ipban.setEnabled(False)
        self.bt_ipban.setObjectName("bt_ipban")
        self.gridLayout.addWidget(self.bt_ipban, 1, 1, 1, 1)
        self.bt_ban = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_ban.setEnabled(False)
        self.bt_ban.setObjectName("bt_ban")
        self.gridLayout.addWidget(self.bt_ban, 0, 1, 1, 1)
        self.bt_kick = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_kick.setEnabled(False)
        self.bt_kick.setObjectName("bt_kick")
        self.gridLayout.addWidget(self.bt_kick, 1, 0, 1, 1)
        self.bt_whisper = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_whisper.setEnabled(False)
        self.bt_whisper.setObjectName("bt_whisper")
        self.gridLayout.addWidget(self.bt_whisper, 0, 0, 1, 1)
        self.RoomLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 21))
        self.menubar.setObjectName("menubar")
        self.menuClient = QtGui.QMenu(self.menubar)
        self.menuClient.setObjectName("menuClient")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuClient.addAction(self.actionExit)
        self.menubar.addAction(self.menuClient.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kolibri Chat Client", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_message.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Insert message here ...", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_send.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_switch.setText(QtGui.QApplication.translate("MainWindow", "Switch Room", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_logout.setText(QtGui.QApplication.translate("MainWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_ipban.setText(QtGui.QApplication.translate("MainWindow", "Ipban/Ipunban", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_ban.setText(QtGui.QApplication.translate("MainWindow", "Ban/Unban", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_kick.setText(QtGui.QApplication.translate("MainWindow", "Kick", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_whisper.setText(QtGui.QApplication.translate("MainWindow", "Whisper", None, QtGui.QApplication.UnicodeUTF8))
        self.menuClient.setTitle(QtGui.QApplication.translate("MainWindow", "Client", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

